### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by InvalidEm** [exordium-dev/exordium#10]
Not sure if this is a bug or not but everytime I tab out of the app this happens http://prntscr.com/qswjuo is it supposed to happen or not, if it is supposed to happen it would be better to remove that.

**Comment by tvOdyssey** [comment]
@InvalidEm What I can do is just make it so that when the application because unfocussed the tooltips automatically remove themselves.

**Comment by tvOdyssey** [comment]
@InvalidEm Adding the function so that when the window because blurred/unfocused didn't help remove the tooltips all the time, but i found a work around. 

```js
  // createTooltips
  if($("[data-toggle='tooltip']").length) {
    $("[data-toggle='tooltip']").tooltip({
      trigger: 'hover'
    });
  }
```

^ seems to have done the trick to add `trigger: hover` which double checks the element is currently being focused on.
