### ISSUE TITLE
White Screen/Update bug

### ISSUE THREAD

**Issue by InvalidEm** [exordium-dev/exordium#11]
**What is the Issue/Bug? (Describe in detail):**
>The screen goes white and it brings up a screen saying new update available and then disappears really fast

**Provide screenshots of the Issue/Bug (if possible):**
>I have been trying to recreate it but it won't do it again. And it disappears really fast

**What were you doing at the time of the Issue/Bug (so we can try and replicate it):**
>I was going through the tabs quite fast but not very fast and the screen went white (just the application) and it said new update available and disappeared really fast.

**What do you think caused the Issue/Bug:** 
>I am not sure as well for this.

**Comment by tvOdyssey** [comment]
@InvalidEm Is there a way for you to record a short clip of the white screen popping in and going out. Will help me figure out what might be the direct cause.

**Comment by InvalidEm** [comment]
> @InvalidEm Is there a way for you to record a short clip of the white screen popping in and going out. Will help me figure out what might be the direct cause.

I'll try to do it and show you

**Comment by tvOdyssey** [comment]
> > @InvalidEm Is there a way for you to record a short clip of the white screen popping in and going out. Will help me figure out what might be the direct cause.
> 
> I'll try to do it and show you

Any news on getting that clip of the white screen bug?

**Comment by tvOdyssey** [comment]
Closing this issue as I have been unable to replicate it, and no more information has been given.
