### ISSUE TITLE
Contact page on exordium.dev

### ISSUE THREAD

**Issue by FriedOctopus** [exordium-dev/exordium#5]
This part of the website in progress has to be centered.

https://exordium.dev/contact/

**Comment by tvOdyssey** [comment]
Thanks for mentioning that! I will get on to resolving it as soon as possible!

**Comment by tvOdyssey** [comment]
I will be updated the contact form design to match the website's bootstrap 4 once the `exordium-wp-core` plugin has been developed more.

However, I have "centered" the contact form with a `<div class="container">` in the meantime. 

Here is an image of the update.

![image](https://user-images.githubusercontent.com/43388217/73124062-aeca6280-3f64-11ea-9fe6-6c5df9ac8f36.png)
