### ISSUE TITLE
Suggestion: Images added to the design layout

### ISSUE THREAD

**Issue by RavenVex** [exordium-dev/exordium#6]
**Describe the suggestion in detail:**
I think that more images should be added to the application, for the purpose of giving users a more comfortable feel during their usage.

**How it can be implemented into the software:**
Background images could be added into certain pages, like sign in or sign up. The images used should reflect our values. Exordium is about environmental protection, therefore we should have images of the environment, like mountains, skies, and other landscapes.

**What are the benefits to this addition:**
Giving the customers a connection through imagery. Connecting to our values, and why we started this project.

**Comment by tvOdyssey** [comment]
The new version of Exordium (0.5.1) will feature images on the sign in page like: 
![image](https://user-images.githubusercontent.com/43388217/73123796-f6032400-3f61-11ea-8fac-8e749bb98b7b.png)
