### ISSUE TITLE
WorldMap Bug

### ISSUE THREAD

**Issue by InvalidEm** [exordium-dev/exordium#9]
What is the Issue/Bug? (Describe in detail):
This is the first run of exordium and I am currently looking at the differents pages on the side and when I cliked on the world map it looks like this

Provide screenshots of the Issue/Bug (if possible):
http://prntscr.com/qswioo zoomed in
http://prntscr.com/qswirv zoomed out

What were you doing at the time of the Issue/Bug (so we can try and replicate it):
I was browsing through the different pages and clicked on worldmap for the first time.

What do you think caused the Issue/Bug: Not sure to be honest, but probably the code.

**Comment by tvOdyssey** [comment]
@InvalidEm I was aware of this issue, wasn't my top concern at the time but I will be sure to fix this in the next released, update if i can figure out what is causing the resizing issue.

**Comment by tvOdyssey** [comment]
@InvalidEm After looking at my code for a while I realised that i forgot to include the `jvectormap.css` file. This has essentially fixed the issue with the size of the map. 

![image](https://user-images.githubusercontent.com/43388217/73130589-68f3b580-3fc9-11ea-8438-85ecae7e990c.png)

@exordium-dev/proposals I was thinking of using mapbox or another 3rd party word map that might show more detail etc. What are your ideas regarding this?

**Comment by InvalidEm** [comment]
> @InvalidEm After looking at my code for a while I realised that i forgot to include the `jvectormap.css` file. This has essentially fixed the issue with the size of the map.
> 
> ![image](https://user-images.githubusercontent.com/43388217/73130589-68f3b580-3fc9-11ea-8438-85ecae7e990c.png)
> 
> @exordium-dev/proposals I was thinking of using mapbox or another 3rd party word map that might show more detail etc. What are your ideas regarding this?

I think using mapbox would be better since it has more customization @tvOdyssey

**Comment by tvOdyssey** [comment]
@InvalidEm @exordium-dev/proposals - Mapbox has been added to Exordium. Here is a picture of the current design, 

![image](https://user-images.githubusercontent.com/43388217/73148102-7623a980-4088-11ea-8277-0e17dea8b2ba.png)
